# Generated by Django 4.0.6 on 2022-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='IGNDPS',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='applicant',
            name='IGNOAPS',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='applicant',
            name='IGNWPS',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='applicant',
            name='NFBS',
            field=models.CharField(default='', max_length=3),
        ),
    ]
